In [1]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

In [4]:
data=DataFrame(np.arange(16).reshape((4,4)),
              index=['Ohio','Colorado','Utah','New York'],
              columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [5]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [6]:
obj['b':'c']

NameError: name 'obj' is not defined

In [8]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [9]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [11]:
data.ix[['Colorado','Utah'], [3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [12]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [13]:
data.ix[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [14]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
data.ix[data.three>5,:3]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [2]:
s1=Series([7.3,4.9,2.6,1.4], index=['a','c','d','e'])
s2=Series([-2.1,-1.6,2.3,3.1,4.7,3.5], index=['a','c','d','e','f','g'])
s1
s2

a   -2.1
c   -1.6
d    2.3
e    3.1
f    4.7
g    3.5
dtype: float64

In [3]:
s1+s2

a    5.2
c    3.3
d    4.9
e    4.5
f    NaN
g    NaN
dtype: float64

In [11]:
df1=DataFrame(np.arange(12).reshape((3,4)), columns=list('abcd'))
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [12]:
df2=DataFrame(np.arange(20).reshape((4,5)), columns=list('abcde'))
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [6]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [10]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [13]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [17]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [18]:
arr=np.arange(12).reshape((3,4))

In [19]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr[0]

array([0, 1, 2, 3])

In [21]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [2]:
frame=DataFrame(np.arange(12).reshape((4,3)), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [3]:
series=frame.ix[0]

In [4]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [5]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [6]:
frame-series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [7]:
series2=Series(range(3), index=['b','e','f'])

In [8]:
series2

b    0
e    1
f    2
dtype: int64

In [9]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [11]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [12]:
series3=frame['d']

In [13]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [14]:
frame.sub(series3, axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [15]:
frame=DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah','Oregon','Texas','Oregon'])

In [16]:
frame

b         d         e
Utah   -0.704907  0.737537 -0.323740
Oregon  1.027807  1.421066  1.345767
Texas  -0.334202 -0.948033 -0.561860
Oregon -0.835859  1.468538 -0.014557

In [17]:
np.abs(frame)

b         d         e
Utah    0.704907  0.737537  0.323740
Oregon  1.027807  1.421066  1.345767
Texas   0.334202  0.948033  0.561860
Oregon  0.835859  1.468538  0.014557

In [18]:
f = lambda x: x.max()-x.min()

In [19]:
frame.apply(f)

b    1.863667
d    2.416571
e    1.907627
dtype: float64

In [20]:
frame.apply(f, axis=1)

Utah      1.442444
Oregon    0.393258
Texas     0.613831
Oregon    2.304397
dtype: float64

In [21]:
def f(x):
    return Series([x.min(), x.max()], index=['min','max'])

In [22]:
frame.apply(f)

b         d         e
min -0.835859 -0.948033 -0.561860
max  1.027807  1.468538  1.345767

In [23]:
format= lambda x: '%.2f' %x

In [24]:
frame.applymap(format)

b      d      e
Utah    -0.70   0.74  -0.32
Oregon   1.03   1.42   1.35
Texas   -0.33  -0.95  -0.56
Oregon  -0.84   1.47  -0.01

In [25]:
obj=Series(range(4), index=['d','a','b','c'])

In [26]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [28]:
obj.sort_index(ascending=False)

d    0
c    3
b    2
a    1
dtype: int64

In [29]:
frame=DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [30]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [31]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [32]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [33]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5